name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Surge
        run: |
          npm install --global surge
          echo ${{ secrets.SURGE_API_KEY }} | surge login
          surge --project ./ --domain ${{ secrets.SURGE_SUBDOMAIN }}.surge.sh
